### ISSUE TITLE
some code issues

### ISSUE THREAD

**Issue by AsimHex** [sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library#1]
In Header file :

//The value of the sense resistor for voltage measurement in Ohms
int _senseResistance = ACS37800_DEFAULT_SENSE_RES;

//The value of the divider resistance for voltage measurement in Ohms
int _dividerResistance = ACS37800_DEFAULT_DIVIDER_RES;

This code is what we have it should be float not int

//The value of the sense resistor for voltage measurement in Ohms
float _senseResistance = ACS37800_DEFAULT_SENSE_RES;

//The value of the divider resistance for voltage measurement in Ohms
float _dividerResistance = ACS37800_DEFAULT_DIVIDER_RES;

**Comment by PaulZC** [comment]
Hi @AsimHex ,
I believe the code is correct.
Looking at _senseResistance:
[Here](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/master/src/SparkFun_ACS37800_Arduino_Library.h#L435) is where it is stored as int
[Here](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/master/src/SparkFun_ACS37800_Arduino_Library.h#L32) is where the default value is defined as const int
[Here](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/master/src/SparkFun_ACS37800_Arduino_Library.h#L418) is the function definition to change the resistance - it expects an int
[Here](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/master/src/SparkFun_ACS37800_Arduino_Library.cpp#L722-L726) is the code for that function - the parameter is int
[Here](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/master/src/SparkFun_ACS37800_Arduino_Library.cpp#L555) is one of two places where the resistance is used. The first thing that happens is that the resistance is **cast to a float**.
I am going to close this as I believe the code is correct, but please reopen if you think I have missed something.
Best wishes,
Paul

**Comment by AsimHex** [comment]
did you try it on arduino uno??
int in arduino uno is from -32,768 to 32,767 and the "_dividerResistance " is 2000000 you define it in your code which will get an error number "bug" second thing resistor should be in float format since it's measurable value and can lead to a higher accuracy if you input the measured one rather typing an integer value

Best wishes 
Asim

**Comment by PaulZC** [comment]
Oh, yes, OK Asim - thank you,
I will investigate that.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Thank you Asim (@AsimHex ),
Corrected in v1.0.2
Best wishes,
Paul
