### ISSUE TITLE
DIO0 Zero Cross SquareWave Output Error

### ISSUE THREAD

**Issue by alipasaoksuz** [sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library#11]
Hi,

I working on ACS37800KMACTR-090B3-I2C with Arduino Uno for I2C reading. DIO0 and DIO1 pins use for I2C address selection. In my board 3 ACS37800 succesfully worked I2C address selection, current and voltage reading. But ı need help for DIO0 Zero Cross Output.

I configured eeprom like this. 17:squarewave_en and 19:zerocrossedgesel set 1 for DIO0 ZC output. But in my DIO0 osscilope graph, ı see ac signal wave. Shouldn't I see a square wave? Can you help me what is it that I miss?
![image](https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/assets/121424162/df38eede-e463-43d3-920e-03b04091553c)

Have a good day :)

**Comment by PaulZC** [comment]
Hi @alipasaoksuz ,

I've never used the zero-crossing feature. But, looking at the [datasheet](https://github.com/sparkfunX/Qwiic_Power_Meter-ACS37800/blob/master/Documents/ACS37800-Datasheet.pdf), I see that it supports pulse mode and square wave mode. It looks like you have the chip configured correctly for square wave mode on the voltage channel (zerocrosschansel = 0).

Please check you have your scope probe grounded correctly - to the ACS37800 GND pad. Be very careful with your GND paths and common-mode voltages, especially if you are using multiple chips with AC power.

Best wishes,
Paul
