### ISSUE TITLE
Example #1 failing on Teensy 4.0

### ISSUE THREAD

**Issue by lps-rocks** [sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library#5]
### Subject of the issue
Example failing on Teensy 4.0 - I'm not sure but it looks like type sizes may be different on this processor causing problems.

### Your workbench
* What platform are you using? Teensy 4.0
* What version of the device are you using? Is there a firmware version? It's Arduino compatible
* How is the device wired to your platform? i2c
* How is everything being powered? regulated 5V, sensor is powered off of Teensy via 3.3 voltage regulator
* Are there any additional details that may help us help you?

### Steps to reproduce
Use example Example1_ReadVoltageCurrentPower

### Expected behaviour
Accurate readings

### Actual behaviour
Looping readings that are incorrect, looks to be a type size misalignment in the code somewhere? 

<pre>eadInstantaneous: vcodes: 0xFF07
readInstantaneous: volts (mV, before correction) is -249.00
readInstantaneous: volts (V, after correction) is -0.55
readInstantaneous: icodes: 0x192
readInstantaneous: amps (A, before correction) is 402.00
readInstantaneous: amps (A, after correction) is 0.44
readInstantaneous: pinstant: 0xFFFE
readInstantaneous: power (mW, before correction) is -2.00
readInstantaneous: power (W, after correction) is -0.16
Volts: -0.55 Amps: 0.44 Watts: -0.16
readInstantaneous: vcodes: 0x38
readInstantaneous: volts (mV, before correction) is 56.00
readInstantaneous: volts (V, after correction) is 0.12
readInstantaneous: icodes: 0x19C
readInstantaneous: amps (A, before correction) is 412.00
readInstantaneous: amps (A, after correction) is 0.45
readInstantaneous: pinstant: 0x4
readInstantaneous: power (mW, before correction) is 4.00
readInstantaneous: power (W, after correction) is 0.32
Volts: 0.12 Amps: 0.45 Watts: 0.32
readInstantaneous: vcodes: 0x154
readInstantaneous: volts (mV, before correction) is 340.00
readInstantaneous: volts (V, after correction) is 0.76
readInstantaneous: icodes: 0x1BC
readInstantaneous: amps (A, before correction) is 444.00
readInstantaneous: amps (A, after correction) is 0.48
readInstantaneous: pinstant: 0x6
readInstantaneous: power (mW, before correction) is 6.00
readInstantaneous: power (W, after correction) is 0.48
Volts: 0.76 Amps: 0.48 Watts: 0.48
readInstantaneous: vcodes: 0x229
readInstantaneous: volts (mV, before correction) is 553.00
readInstantaneous: volts (V, after correction) is 1.23
readInstantaneous: icodes: 0x1D0
readInstantaneous: amps (A, before correction) is 464.00
readInstantaneous: amps (A, after correction) is 0.51
readInstantaneous: pinstant: 0x7
readInstantaneous: power (mW, before correction) is 7.00
readInstantaneous: power (W, after correction) is 0.56
Volts: 1.23 Amps: 0.51 Watts: 0.56
readInstantaneous: vcodes: 0x239
readInstantaneous: volts (mV, before correction) is 569.00
readInstantaneous: volts (V, after correction) is 1.27
readInstantaneous: icodes: 0x196
readInstantaneous: amps (A, before correction) is 406.00
readInstantaneous: amps (A, after correction) is 0.44
readInstantaneous: pinstant: 0x6
readInstantaneous: power (mW, before correction) is 6.00
readInstantaneous: power (W, after correction) is 0.48
Volts: 1.27 Amps: 0.44 Watts: 0.48
readInstantaneous: vcodes: 0x23D
readInstantaneous: volts (mV, before correction) is 573.00
readInstantaneous: volts (V, after correction) is 1.28
readInstantaneous: icodes: 0x1D4
readInstantaneous: amps (A, before correction) is 468.00
readInstantaneous: amps (A, after correction) is 0.51
readInstantaneous: pinstant: 0x6
readInstantaneous: power (mW, before correction) is 6.00
readInstantaneous: power (W, after correction) is 0.48
Volts: 1.28 Amps: 0.51 Watts: 0.48
readInstantaneous: vcodes: 0x130
readInstantaneous: volts (mV, before correction) is 304.00
readInstantaneous: volts (V, after correction) is 0.68
readInstantaneous: icodes: 0x1D0
readInstantaneous: amps (A, before correction) is 464.00
readInstantaneous: amps (A, after correction) is 0.51
readInstantaneous: pinstant: 0x2
readInstantaneous: power (mW, before correction) is 2.00
readInstantaneous: power (W, after correction) is 0.16
Volts: 0.68 Amps: 0.51 Watts: 0.16
readInstantaneous: vcodes: 0x12
readInstantaneous: volts (mV, before correction) is 18.00
readInstantaneous: volts (V, after correction) is 0.04
readInstantaneous: icodes: 0x1A6
readInstantaneous: amps (A, before correction) is 422.00
readInstantaneous: amps (A, after correction) is 0.46
readInstantaneous: pinstant: 0xFFFB
readInstantaneous: power (mW, before correction) is -5.00
readInstantaneous: power (W, after correction) is -0.40
Volts: 0.04 Amps: 0.46 Watts: -0.40
readInstantaneous: vcodes: 0xFE2E
readInstantaneous: volts (mV, before correction) is -466.00
readInstantaneous: volts (V, after correction) is -1.04
readInstantaneous: icodes: 0x1C6
readInstantaneous: amps (A, before correction) is 454.00
readInstantaneous: amps (A, after correction) is 0.50
readInstantaneous: pinstant: 0xFFF9
readInstantaneous: power (mW, before correction) is -7.00
readInstantaneous: power (W, after correction) is -0.56
Volts: -1.04 Amps: 0.50 Watts: -0.56
readInstantaneous: vcodes: 0xFD5B
readInstantaneous: volts (mV, before correction) is -677.00
readInstantaneous: volts (V, after correction) is -1.51
readInstantaneous: icodes: 0x1DE
readInstantaneous: amps (A, before correction) is 478.00
readInstantaneous: amps (A, after correction) is 0.52
readInstantaneous: pinstant: 0xFFF6
readInstantaneous: power (mW, before correction) is -10.00
readInstantaneous: power (W, after correction) is -0.80
Volts: -1.51 Amps: 0.52 Watts: -0.80
readInstantaneous: vcodes: 0xFD39
readInstantaneous: volts (mV, before correction) is -711.00
readInstantaneous: volts (V, after correction) is -1.58
readInstantaneous: icodes: 0x1AE
readInstantaneous: amps (A, before correction) is 430.00
readInstantaneous: amps (A, after correction) is 0.47
readInstantaneous: pinstant: 0xFFF7
readInstantaneous: power (mW, before correction) is -9.00
readInstantaneous: power (W, after correction) is -0.72
Volts: -1.58 Amps: 0.47 Watts: -0.72
readInstantaneous: vcodes: 0xFDC0
readInstantaneous: volts (mV, before correction) is -576.00
readInstantaneous: volts (V, after correction) is -1.28
readInstantaneous: icodes: 0x1CA
readInstantaneous: amps (A, before correction) is 458.00
readInstantaneous: amps (A, after correction) is 0.50
readInstantaneous: pinstant: 0xFFF9
readInstantaneous: power (mW, before correction) is -7.00
readInstantaneous: power (W, after correction) is -0.56
Volts: -1.28 Amps: 0.50 Watts: -0.56
readInstantaneous: vcodes: 0xFE93
readInstantaneous: volts (mV, before correction) is -365.00
readInstantaneous: volts (V, after correction) is -0.81
readInstantaneous: icodes: 0x1A0
readInstantaneous: amps (A, before correction) is 416.00
readInstantaneous: amps (A, after correction) is 0.45
readInstantaneous: pinstant: 0xFFFD
readInstantaneous: power (mW, before correction) is -3.00
readInstantaneous: power (W, after correction) is -0.24
Volts: -0.81 Amps: 0.45 Watts: -0.24
readInstantaneous: vcodes: 0xFF9B
readInstantaneous: volts (mV, before correction) is -101.00
readInstantaneous: volts (V, after correction) is -0.22
readInstantaneous: icodes: 0x1B4
readInstantaneous: amps (A, before correction) is 436.00
readInstantaneous: amps (A, after correction) is 0.48
readInstantaneous: pinstant: 0x3
readInstantaneous: power (mW, before correction) is 3.00
readInstantaneous: power (W, after correction) is 0.24
Volts: -0.22 Amps: 0.48 Watts: 0.24
readInstantaneous: vcodes: 0x176
readInstantaneous: volts (mV, before correction) is 374.00
readInstantaneous: volts (V, after correction) is 0.83
readInstantaneous: icodes: 0x19A
readInstantaneous: amps (A, before correction) is 410.00
readInstantaneous: amps (A, after correction) is 0.45
readInstantaneous: pinstant: 0x6
readInstantaneous: power (mW, before correction) is 6.00
readInstantaneous: power (W, after correction) is 0.48
Volts: 0.83 Amps: 0.45 Watts: 0.48
readInstantaneous: vcodes: 0x230
readInstantaneous: volts (mV, before correction) is 560.00
readInstantaneous: volts (V, after correction) is 1.25
readInstantaneous: icodes: 0x1B8
readInstantaneous: amps (A, before correction) is 440.00
readInstantaneous: amps (A, after correction) is 0.48
readInstantaneous: pinstant: 0x9
readInstantaneous: power (mW, before correction) is 9.00
readInstantaneous: power (W, after correction) is 0.72
Volts: 1.25 Amps: 0.48 Watts: 0.72
readInstantaneous: vcodes: 0x26C
readInstantaneous: volts (mV, before correction) is 620.00
readInstantaneous: volts (V, after correction) is 1.38
readInstantaneous: icodes: 0x1B2
readInstantaneous: amps (A, before correction) is 434.00
readInstantaneous: amps (A, after correction) is 0.47
readInstantaneous: pinstant: 0x8
readInstantaneous: power (mW, before correction) is 8.00
readInstantaneous: power (W, after correction) is 0.64
Volts: 1.38 Amps: 0.47 Watts: 0.64

</pre>

**Comment by PaulZC** [comment]
Hi James (@lps-rocks ),

It looks like you are measuring a current of around 0.5 Amps.
Your voltage is drifting at around +/- 1.5V.
The power measurement seems correct.
This looks OK to me - but I don't know what voltage and current you are expecting to see?

Please tell me a bit more about the voltage and current you are trying to measure.
How do you have the ACS37800 connected into your circuit?
Can you upload a sketch or photo?
Are you measuring high side, or low side?
Maybe your GND is floating?

Please check the _draft_ hook-up guide for details:

https://github.com/sparkfunX/Qwiic_Power_Meter-ACS37800/blob/master/HOOKUP.md

Best wishes,
Paul

**Comment by lps-rocks** [comment]
@PaulZC - I'm expecting a current measurement of a little over 1 amp @ 24.14VDC - I'm measuring on the high side using the simple high side measurement hookup example. 

I have two of these sensors in different power supplies. I hooked one up, used Example 2 to change it's i2c address to 0x61 from the default of 0x60 and confirmed it did change the address. So, the devices are hooked up to the i2c bus correctly. 

Here's where things get weird though, initially with example 1, I get the following from *both* sensors addresese which I use on line https://github.com/sparkfun/SparkFun_ACS37800_Power_Monitor_Arduino_Library/blob/370e4c073422e663841b440a0b0462836f532eb6/examples/Example1_ReadVoltageCurrentPower/Example1_ReadVoltageCurrentPower.ino#L27

<pre>
ACS37800 Example
readRegister: requestFrom returned: 0
getCurrentCoarseGain: readRegister (1B) returned: 1
ACS37800::begin: failed! getCurrentCoarseGain returned: 1
ACS37800 not detected. Check connections and I2C address. Freezing..
</pre>

The sensors are clearly there and responding because I was able to modify the EEPROM on one of them using Example 2.

**Comment by PaulZC** [comment]
I can't explain why begin is failing on _both_ sensors. It will fail on the device with address 0x61 unless you change the begin to match:

```
if (mySensor.begin(0x61) == false)
```

Very strange... If you are able to change the address then the basic I2C functionality is working. ```setI2Caddress``` calls both ```readRegister``` and ```writeRegister```. Those are the functions which underpin all of the I2C communication.

The ```readRegister: requestFrom returned: 0``` error indicates the ACS37800 returned zero bytes, instead of the four bytes expected.

Have you power-cycled the sensor with address 0x61? The address change only happens after a power cycle. I'm wondering if both are still using 0x60 and you're getting bus collisions as a result?

**Comment by lps-rocks** [comment]
So, what's very weird, is Example 2 worked just fine without fixing grounding or the pull-ups on the i2c lines - Don't ask me why. 

I added external pull-ups and disabled the ones on the sensors and tied my Teensy's ground to the PSU grounds and tied the PSU grounds together. 

Now I'm getting reliable readings from both sensors.

**Comment by PaulZC** [comment]
Case closed?! ;-)

Please re-open if you need more help with this.

Best wishes,
Paul
